
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Filters.GtkViews
{
	public partial class BreakdownKindJournalFilterView
	{
		private global::Gtk.HBox hbox2;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gamma.Widgets.yEnumComboBox comboShowArchive;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Filters.GtkViews.BreakdownKindJournalFilterView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Filters.GtkViews.BreakdownKindJournalFilterView";
			// Container child Vodovoz.Filters.GtkViews.BreakdownKindJournalFilterView.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Архивные:");
			this.hbox2.Add(this.ylabel1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.ylabel1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.comboShowArchive = new global::Gamma.Widgets.yEnumComboBox();
			this.comboShowArchive.Name = "comboShowArchive";
			this.comboShowArchive.ShowSpecialStateAll = false;
			this.comboShowArchive.ShowSpecialStateNot = false;
			this.comboShowArchive.UseShortTitle = false;
			this.comboShowArchive.DefaultFirst = false;
			this.hbox2.Add(this.comboShowArchive);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.comboShowArchive]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add(this.hbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
