
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Logistic
{
	public partial class AssignedDriverView
	{
		private global::Gtk.HBox hbox3;

		private global::Gtk.Label labelFiller;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hboxTopMenu;

		private global::Gamma.GtkWidgets.yButton ybuttonAccept;

		private global::Gamma.GtkWidgets.yButton ybuttonCancel;

		private global::Gtk.HBox hbox1;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::QS.Widgets.GtkUI.EntityViewModelEntry entryDriver;

		private global::Gamma.GtkWidgets.yLabel ylabel2;

		private global::QS.Widgets.GtkUI.DateRangePicker datepicker;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Logistic.AssignedDriverView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Logistic.AssignedDriverView";
			// Container child Vodovoz.Views.Logistic.AssignedDriverView.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.labelFiller = new global::Gtk.Label();
			this.labelFiller.WidthRequest = 30;
			this.labelFiller.Name = "labelFiller";
			this.hbox3.Add(this.labelFiller);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.labelFiller]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxTopMenu = new global::Gtk.HBox();
			this.hboxTopMenu.Name = "hboxTopMenu";
			this.hboxTopMenu.Spacing = 6;
			// Container child hboxTopMenu.Gtk.Box+BoxChild
			this.ybuttonAccept = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonAccept.CanFocus = true;
			this.ybuttonAccept.Name = "ybuttonAccept";
			this.ybuttonAccept.UseUnderline = true;
			this.ybuttonAccept.Label = global::Mono.Unix.Catalog.GetString("Подтвердить");
			global::Gtk.Image w2 = new global::Gtk.Image();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-yes", global::Gtk.IconSize.Menu);
			this.ybuttonAccept.Image = w2;
			this.hboxTopMenu.Add(this.ybuttonAccept);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxTopMenu[this.ybuttonAccept]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxTopMenu.Gtk.Box+BoxChild
			this.ybuttonCancel = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonCancel.CanFocus = true;
			this.ybuttonCancel.Name = "ybuttonCancel";
			this.ybuttonCancel.UseUnderline = true;
			this.ybuttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			global::Gtk.Image w4 = new global::Gtk.Image();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.ybuttonCancel.Image = w4;
			this.hboxTopMenu.Add(this.ybuttonCancel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxTopMenu[this.ybuttonCancel]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add(this.hboxTopMenu);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxTopMenu]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Водитель:");
			this.hbox1.Add(this.ylabel1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabel1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryDriver = new global::QS.Widgets.GtkUI.EntityViewModelEntry();
			this.entryDriver.Events = ((global::Gdk.EventMask)(256));
			this.entryDriver.Name = "entryDriver";
			this.entryDriver.CanEditReference = true;
			this.hbox1.Add(this.entryDriver);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entryDriver]));
			w8.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabel2 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel2.Name = "ylabel2";
			this.ylabel2.LabelProp = global::Mono.Unix.Catalog.GetString("Период:");
			this.hbox1.Add(this.ylabel2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabel2]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.datepicker = new global::QS.Widgets.GtkUI.DateRangePicker();
			this.datepicker.WidthRequest = 250;
			this.datepicker.Events = ((global::Gdk.EventMask)(256));
			this.datepicker.Name = "datepicker";
			this.datepicker.StartDate = new global::System.DateTime(0);
			this.datepicker.EndDate = new global::System.DateTime(0);
			this.hbox1.Add(this.datepicker);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.datepicker]));
			w10.Position = 3;
			w10.Expand = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox3.Add(this.vbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox1]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.Add(this.hbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
