
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.ReportsParameters.Orders
{
	public partial class OrderChangesReport
	{
		private global::Gtk.VBox vboxReport;

		private global::Gtk.HBox hboxDate;

		private global::Gamma.GtkWidgets.yLabel ylabelDate;

		private global::QS.Widgets.GtkUI.DateRangePicker dateperiodpicker;

		private global::Gamma.GtkWidgets.yLabel ylabelDateWarning;

		private global::Gtk.Table table1;

		private global::Gamma.Widgets.yEnumComboBox comboIssueType;

		private global::Gamma.Widgets.ySpecComboBox comboOrganization;

		private global::Gamma.GtkWidgets.yLabel ylabelChangeType;

		private global::Gamma.GtkWidgets.yLabel ylabelIssueType;

		private global::Gamma.GtkWidgets.yLabel ylabelOrganization;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewChangeTypes;

		private global::Gamma.GtkWidgets.yTextView ytextview1;

		private global::Gtk.Button buttonCreateReport;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.ReportsParameters.Orders.OrderChangesReport
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.ReportsParameters.Orders.OrderChangesReport";
			// Container child Vodovoz.ReportsParameters.Orders.OrderChangesReport.Gtk.Container+ContainerChild
			this.vboxReport = new global::Gtk.VBox();
			this.vboxReport.Name = "vboxReport";
			this.vboxReport.Spacing = 6;
			// Container child vboxReport.Gtk.Box+BoxChild
			this.hboxDate = new global::Gtk.HBox();
			this.hboxDate.Name = "hboxDate";
			this.hboxDate.Spacing = 6;
			// Container child hboxDate.Gtk.Box+BoxChild
			this.ylabelDate = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelDate.Name = "ylabelDate";
			this.ylabelDate.LabelProp = global::Mono.Unix.Catalog.GetString("Дата:");
			this.hboxDate.Add(this.ylabelDate);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hboxDate[this.ylabelDate]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hboxDate.Gtk.Box+BoxChild
			this.dateperiodpicker = new global::QS.Widgets.GtkUI.DateRangePicker();
			this.dateperiodpicker.WidthRequest = 280;
			this.dateperiodpicker.Events = ((global::Gdk.EventMask)(256));
			this.dateperiodpicker.Name = "dateperiodpicker";
			this.dateperiodpicker.StartDate = new global::System.DateTime(0);
			this.dateperiodpicker.EndDate = new global::System.DateTime(0);
			this.hboxDate.Add(this.dateperiodpicker);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxDate[this.dateperiodpicker]));
			w2.Position = 1;
			w2.Expand = false;
			this.vboxReport.Add(this.hboxDate);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxReport[this.hboxDate]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxReport.Gtk.Box+BoxChild
			this.ylabelDateWarning = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelDateWarning.Name = "ylabelDateWarning";
			this.ylabelDateWarning.Xalign = 0F;
			this.ylabelDateWarning.LabelProp = global::Mono.Unix.Catalog.GetString("<span color=\"Red\">Выбранный период более 2-х недель, \nотчет может выполняться оче" +
					"нь долго!</span>");
			this.ylabelDateWarning.UseMarkup = true;
			this.vboxReport.Add(this.ylabelDateWarning);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxReport[this.ylabelDateWarning]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vboxReport.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboIssueType = new global::Gamma.Widgets.yEnumComboBox();
			this.comboIssueType.Name = "comboIssueType";
			this.comboIssueType.ShowSpecialStateAll = false;
			this.comboIssueType.ShowSpecialStateNot = false;
			this.comboIssueType.UseShortTitle = false;
			this.comboIssueType.DefaultFirst = true;
			this.table1.Add(this.comboIssueType);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.comboIssueType]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboOrganization = new global::Gamma.Widgets.ySpecComboBox();
			this.comboOrganization.Name = "comboOrganization";
			this.comboOrganization.AddIfNotExist = false;
			this.comboOrganization.DefaultFirst = false;
			this.comboOrganization.ShowSpecialStateAll = false;
			this.comboOrganization.ShowSpecialStateNot = false;
			this.table1.Add(this.comboOrganization);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.comboOrganization]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelChangeType = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelChangeType.Name = "ylabelChangeType";
			this.ylabelChangeType.Xalign = 1F;
			this.ylabelChangeType.LabelProp = global::Mono.Unix.Catalog.GetString("Типы изменений:");
			this.table1.Add(this.ylabelChangeType);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelChangeType]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelIssueType = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelIssueType.Name = "ylabelIssueType";
			this.ylabelIssueType.Xalign = 1F;
			this.ylabelIssueType.LabelProp = global::Mono.Unix.Catalog.GetString("Тип проблем:");
			this.table1.Add(this.ylabelIssueType);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelIssueType]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelOrganization = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelOrganization.Name = "ylabelOrganization";
			this.ylabelOrganization.Xalign = 1F;
			this.ylabelOrganization.LabelProp = global::Mono.Unix.Catalog.GetString("Организация:");
			this.table1.Add(this.ylabelOrganization);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelOrganization]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ytreeviewChangeTypes = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewChangeTypes.CanFocus = true;
			this.ytreeviewChangeTypes.Name = "ytreeviewChangeTypes";
			this.table1.Add(this.ytreeviewChangeTypes);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.ytreeviewChangeTypes]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxReport.Add(this.table1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxReport[this.table1]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vboxReport.Gtk.Box+BoxChild
			this.ytextview1 = new global::Gamma.GtkWidgets.yTextView();
			this.ytextview1.Buffer.Text = global::Mono.Unix.Catalog.GetString("Описание:\nВ отчет попадает информация об изменении полей заказа \nи товаров заказа" +
					", после того как заказ был доставлен.\nПоиск идет по заказам за выбранный интерва" +
					"л с выбранными \nтипами изменений и организацией .");
			this.ytextview1.CanFocus = true;
			this.ytextview1.Name = "ytextview1";
			this.ytextview1.Editable = false;
			this.vboxReport.Add(this.ytextview1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxReport[this.ytextview1]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vboxReport.Gtk.Box+BoxChild
			this.buttonCreateReport = new global::Gtk.Button();
			this.buttonCreateReport.Sensitive = false;
			this.buttonCreateReport.CanFocus = true;
			this.buttonCreateReport.Name = "buttonCreateReport";
			this.buttonCreateReport.UseUnderline = true;
			this.buttonCreateReport.Label = global::Mono.Unix.Catalog.GetString("Сформировать отчет");
			this.vboxReport.Add(this.buttonCreateReport);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxReport[this.buttonCreateReport]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 5;
			w13.Expand = false;
			w13.Fill = false;
			this.Add(this.vboxReport);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.ylabelDateWarning.Hide();
			this.Hide();
		}
	}
}
