
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Logistic
{
	public partial class CarRepairScheduleView
	{
		private global::Gtk.HBox hbox3;

		private global::Gtk.Label labelFiller;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hboxTopMenu;

		private global::Gamma.GtkWidgets.yButton ybuttonAccept;

		private global::Gamma.GtkWidgets.yButton ybuttonCancel;

		private global::Gtk.HBox hbox1;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::QS.Widgets.GtkUI.SpecialListComboBox comboBreakdownKind;

		private global::Gamma.GtkWidgets.yLabel ylabel2;

		private global::QS.Widgets.GtkUI.DateRangePicker datepicker;

		private global::Gtk.HBox hbox5;

		private global::Gtk.VBox vbox5;

		private global::Gamma.GtkWidgets.yLabel ylabel3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTextView ytextComment;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Logistic.CarRepairScheduleView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Logistic.CarRepairScheduleView";
			// Container child Vodovoz.Views.Logistic.CarRepairScheduleView.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.labelFiller = new global::Gtk.Label();
			this.labelFiller.WidthRequest = 30;
			this.labelFiller.Name = "labelFiller";
			this.hbox3.Add(this.labelFiller);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.labelFiller]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxTopMenu = new global::Gtk.HBox();
			this.hboxTopMenu.Name = "hboxTopMenu";
			this.hboxTopMenu.Spacing = 6;
			// Container child hboxTopMenu.Gtk.Box+BoxChild
			this.ybuttonAccept = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonAccept.CanFocus = true;
			this.ybuttonAccept.Name = "ybuttonAccept";
			this.ybuttonAccept.UseUnderline = true;
			this.ybuttonAccept.Label = global::Mono.Unix.Catalog.GetString("Подтвердить");
			global::Gtk.Image w2 = new global::Gtk.Image();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-yes", global::Gtk.IconSize.Menu);
			this.ybuttonAccept.Image = w2;
			this.hboxTopMenu.Add(this.ybuttonAccept);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxTopMenu[this.ybuttonAccept]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxTopMenu.Gtk.Box+BoxChild
			this.ybuttonCancel = new global::Gamma.GtkWidgets.yButton();
			this.ybuttonCancel.CanFocus = true;
			this.ybuttonCancel.Name = "ybuttonCancel";
			this.ybuttonCancel.UseUnderline = true;
			this.ybuttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			global::Gtk.Image w4 = new global::Gtk.Image();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.ybuttonCancel.Image = w4;
			this.hboxTopMenu.Add(this.ybuttonCancel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxTopMenu[this.ybuttonCancel]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add(this.hboxTopMenu);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxTopMenu]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Вид поломки:");
			this.hbox1.Add(this.ylabel1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabel1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.comboBreakdownKind = new global::QS.Widgets.GtkUI.SpecialListComboBox();
			this.comboBreakdownKind.Name = "comboBreakdownKind";
			this.comboBreakdownKind.AddIfNotExist = false;
			this.comboBreakdownKind.DefaultFirst = false;
			this.comboBreakdownKind.ShowSpecialStateAll = false;
			this.comboBreakdownKind.ShowSpecialStateNot = true;
			this.hbox1.Add(this.comboBreakdownKind);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.comboBreakdownKind]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ylabel2 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel2.Name = "ylabel2";
			this.ylabel2.LabelProp = global::Mono.Unix.Catalog.GetString("Период:");
			this.hbox1.Add(this.ylabel2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ylabel2]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.datepicker = new global::QS.Widgets.GtkUI.DateRangePicker();
			this.datepicker.WidthRequest = 250;
			this.datepicker.Events = ((global::Gdk.EventMask)(256));
			this.datepicker.Name = "datepicker";
			this.datepicker.StartDate = new global::System.DateTime(0);
			this.datepicker.EndDate = new global::System.DateTime(0);
			this.hbox1.Add(this.datepicker);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.datepicker]));
			w10.Position = 3;
			w10.Expand = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.ylabel3 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel3.Name = "ylabel3";
			this.ylabel3.LabelProp = global::Mono.Unix.Catalog.GetString("Комментарий");
			this.vbox5.Add(this.ylabel3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.ylabel3]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytextComment = new global::Gamma.GtkWidgets.yTextView();
			this.ytextComment.WidthRequest = 650;
			this.ytextComment.HeightRequest = 100;
			this.ytextComment.CanFocus = true;
			this.ytextComment.Name = "ytextComment";
			this.ytextComment.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow.Add(this.ytextComment);
			this.vbox5.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow]));
			w14.Position = 1;
			w14.Expand = false;
			this.hbox5.Add(this.vbox5);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox5]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w16.Position = 2;
			this.hbox3.Add(this.vbox1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox1]));
			w17.Position = 1;
			this.Add(this.hbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
